version: "2.1"

volumes:
  letsencrypt:

services:

  traefik:
    build: ./traefik
    labels:
      io.balena.features.balena-socket: true
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - letsencrypt:/letsencrypt
